# Generated by Django 4.2.4 on 2023-08-25 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacina',
            name='data_reforco',
        ),
        migrations.AddField(
            model_name='vacina',
            name='nova_dose',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacina',
            name='validade',
            field=models.CharField(max_length=50),
        ),
    ]
