# Generated by Django 4.2.4 on 2023-09-09 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0004_alter_fichadog_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichadog',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
