# Generated by Django 4.2.4 on 2023-08-25 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_reservabanho'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservabanho',
            name='total',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reservabanho',
            name='cachorro',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reservabanho',
            name='observacoes',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
