# Generated by Django 4.2.4 on 2023-09-04 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_reservabanho_total_alter_reservabanho_cachorro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservaday',
            name='horario_alimentacao',
        ),
        migrations.RemoveField(
            model_name='reservaday',
            name='horario_personalizado',
        ),
        migrations.AddField(
            model_name='reservabanho',
            name='metodo_de_pagamento',
            field=models.CharField(choices=[('Cartão de Crédito', 'Cartão de Crédito'), ('Cartão de Debito', 'Cartão de Debito'), ('Dinheiro', 'Dinheiro'), ('Pix', 'Pix')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservaday',
            name='autorizacao_para_cuidados_medicos',
            field=models.BooleanField(choices=[(False, 'Não'), (True, 'Sim')], default=True),
        ),
    ]
