# Generated by Django 4.2.4 on 2023-09-05 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_remove_reservaday_horario_alimentacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservabanho',
            name='metodo_de_pagamento',
            field=models.CharField(blank=True, choices=[('Cartão de Crédito', 'Cartão de Crédito'), ('Cartão de Debito', 'Cartão de Debito'), ('Dinheiro', 'Dinheiro'), ('Pix', 'Pix')], max_length=20, null=True),
        ),
    ]
